apiVersion: v1
kind: Pod
metadata:
  labels:
  {{- range $key, $val := .Values.labels }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
spec:
  containers:
    - name: busybox
      image: {{ template "image" .}}
      imagePullPolicy: "{{ .Values.container.imagePullPolicy}}"
      command:
      {{- with .Values.container.command -}}
        {{ toYaml .|nindent 6 }}
      {{- end }}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
